BOARD = GENERIC_RP_RP2040

OLED_ENABLE = yes
OLED_DRIVER = SSD1306
TAP_DANCE_ENABLE = no

BOOTMAGIC_ENABLE = yes

ENCODER_ENABLE = yes

RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
WS2812_DRIVER = vendor
